[rospy.client][INFO] 2020-11-17 05:11:28,471: init_node, name[/train_10336_1605589888467], pid[10336]
[xmlrpc][INFO] 2020-11-17 05:11:28,472: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-17 05:11:28,472: Started XML-RPC server [http://luigi:45121/]
[rospy.init][INFO] 2020-11-17 05:11:28,473: ROS Slave URI: [http://luigi:45121/]
[rospy.impl.masterslave][INFO] 2020-11-17 05:11:28,473: _ready: http://luigi:45121/
[rospy.registration][INFO] 2020-11-17 05:11:28,474: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-17 05:11:28,475: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-17 05:11:28,573: registered with master
[rospy.rosout][INFO] 2020-11-17 05:11:28,574: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-17 05:11:28,579: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-17 05:11:28,580: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-17 05:11:28,600: topic[/odom] adding connection to [http://192.168.0.201:37487/], count 0
[rospy.internal][INFO] 2020-11-17 05:11:28,833: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-17 05:11:38,896: topic[/bev/flow_image] adding connection to [http://192.168.0.201:38225/], count 0
[rospy.internal][INFO] 2020-11-17 05:11:38,898: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:38225/], count 0
[rospy.core][INFO] 2020-11-17 05:11:42,032: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-11-17 05:11:42,036: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-17 05:11:42,037: topic[/bev/flow_image] removing connection to http://192.168.0.201:38225/
[rospy.internal][INFO] 2020-11-17 05:11:42,037: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:38225/
[rospy.internal][INFO] 2020-11-17 05:11:42,038: topic[/odom] removing connection to http://192.168.0.201:37487/
[rospy.impl.masterslave][INFO] 2020-11-17 05:11:42,038: atexit
[rospy.internal][WARNING] 2020-11-17 05:11:42,039: Unknown error initiating TCP/IP socket to 192.168.0.201:43553 (http://192.168.0.201:38225/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-11-17 05:11:42,040: Unknown error initiating TCP/IP socket to 192.168.0.201:47607 (http://192.168.0.201:37487/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

