[rospy.client][INFO] 2020-11-12 03:19:14,240: init_node, name[/train_8965_1605151154235], pid[8965]
[xmlrpc][INFO] 2020-11-12 03:19:14,241: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-12 03:19:14,241: Started XML-RPC server [http://luigi:45349/]
[rospy.init][INFO] 2020-11-12 03:19:14,242: ROS Slave URI: [http://luigi:45349/]
[rospy.impl.masterslave][INFO] 2020-11-12 03:19:14,242: _ready: http://luigi:45349/
[rospy.registration][INFO] 2020-11-12 03:19:14,243: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-12 03:19:14,243: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-12 03:19:14,342: registered with master
[rospy.rosout][INFO] 2020-11-12 03:19:14,343: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-12 03:19:14,348: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-12 03:19:14,349: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-12 03:19:14,371: topic[/odom] adding connection to [http://192.168.0.201:46833/], count 0
[rospy.internal][INFO] 2020-11-12 03:19:14,373: topic[/bev/flow_image] adding connection to [http://192.168.0.201:37255/], count 0
[rospy.internal][INFO] 2020-11-12 03:19:14,376: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:37255/], count 0
[rospy.internal][INFO] 2020-11-12 03:19:14,593: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2020-11-12 03:19:38,892: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-12 03:19:38,897: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-12 03:19:38,897: topic[/bev/flow_image] removing connection to http://192.168.0.201:37255/
[rospy.internal][INFO] 2020-11-12 03:19:38,898: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:37255/
[rospy.internal][INFO] 2020-11-12 03:19:38,898: topic[/odom] removing connection to http://192.168.0.201:46833/
[rospy.impl.masterslave][INFO] 2020-11-12 03:19:38,898: signal-2
[rospy.internal][WARNING] 2020-11-12 03:19:38,899: Unknown error initiating TCP/IP socket to 192.168.0.201:34869 (http://192.168.0.201:46833/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-11-12 03:19:39,392: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-12 03:19:39,436: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-12 03:19:39,453: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-12 03:19:39,484: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-12 03:19:39,494: signal_shutdown [atexit]
